### ISSUE TITLE
你好作者，这个beego版本是1.x还是2.x ?

### ISSUE THREAD

**Issue by zhanglibo11** [yuxingfei/beego-admin#14]

**Comment by yuxingfei** [comment]
现在beego最新版是1.几的------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zhanglibo11&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月6日(星期六) 中午1:20
收件人:&nbsp;&quot;yuxingfei/beego-admin&quot;<beego-admin@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yuxingfei/beego-admin] 你好作者，这个beego版本是1.x还是2.x ? (#14)

**Comment by yuxingfei** [comment]
beego-admin v2.0,1 for beego v2.0.1 updated.

**Comment by zhanglibo11** [comment]
> beego-admin v2.0,1 for beego v2.0.1 updated.

嗯  这个升级好像没多麻烦！我也升级到2.02了。你这个后台挺好用。

**Comment by yuxingfei** [comment]
谢谢支持------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zhanglibo11&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月7日(星期天) 晚上10:07
收件人:&nbsp;&quot;yuxingfei/beego-admin&quot;<beego-admin@noreply.github.com&gt;;
抄送:&nbsp;&quot;yuxingfei&quot;<474949931@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yuxingfei/beego-admin] 你好作者，这个beego版本是1.x还是2.x ? (#14)
