### ISSUE TITLE
template block渲染无效的问题

### ISSUE THREAD

**Issue by kxg3030** [yuxingfei/beego-admin#19]
在这篇文章中：
https://blog.csdn.net/QQ474949931/article/details/112853257
如果多个子界面继承了main.html，渲染的内容并不会改变，而是第一个渲染的界面，请问这个问题能解决吗

**Comment by yuxingfei** [comment]
界面方面 还是建议用beego框架 gin框架针对接口使用的比较多一点 不太适合界面方面的处理

**Comment by yuxingfei** [comment]
.
